name: iqra_connect
description: "Iqra Connect Job Application"
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ---------------- FIREBASE (ANDROID SAFE) ----------------
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.2.10

  # ---------------- ADS ----------------
  google_mobile_ads: ^5.2.0

  # ---------------- STATE ----------------
  provider: ^6.1.2

  # ---------------- STORAGE ----------------
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ---------------- AUTH ----------------
  google_sign_in: ^6.2.1

  # ---------------- UTILITIES ----------------
  url_launcher: ^6.3.0
  intl: ^0.19.0
  uuid: ^4.5.1
  font_awesome_flutter: ^10.7.0

  # ---------------- NOTIFICATIONS ----------------
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appicon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
